### ISSUE TITLE
Make a microphone replica

### ISSUE THREAD

**Issue by CaptainBobSim** [CaptainBobSim/The-Cessna-172-Project-V3#144]

**Comment by EverticalGuy** [comment]
I talked to my pilot friend, he should hopefully be getting measurements and pictures of the microphone today so we can make an accurate replica. From what he said though, that microphone is actually an "emergency microphone" and they don't really use it because they use the microphone that's built into their headsets.

**Comment by CaptainBobSim** [comment]
Perfect! That will be extremely helpful!
Hopefully we don't find ourselves in an emergency, but once we do we'll be ready!

**Comment by CaptainBobSim** [comment]
Thank you Everett!
