### ISSUE TITLE
Fit Small Kovinator Instruments into C172 Project

### ISSUE THREAD

**Issue by CaptainBobSim** [CaptainBobSim/The-Cessna-172-Project-V3#168]
Kovinator made awesome instruments! Now I just need to fit them into the project

**Comment by CaptainBobSim** [comment]
These look really spiffy @Kovinator 
![12 29 2022 Image](https://user-images.githubusercontent.com/76851401/209993024-fc6ff541-f8d5-41d3-9156-ea14d9ed80a7.PNG)

**Comment by Kovinator** [comment]
Happy New Year!!!!!

Here are some pics of the small instrument using the junction box.

[image: image2.jpeg]

Need to paint the EGT needle but which color red or yellow?

[image: image1.jpeg]
Here is a picture from the top.


[image: image3.jpeg]


Here is from the side. I cut off all the extra servo wire and crimped on
dupont connectors to keep
things nice and clean. LEDs have resistor soldered in with the harness.

[image: image0.jpeg]

Time for a night flight. I may switch to yellow instead of white. What
color are you going to use? I also added a POT so I can dim them using PWM
in mobiflight.

**Comment by CaptainBobSim** [comment]
Did the images attach correctly? I don't know if they do when using email.

**Comment by CaptainBobSim** [comment]
I think yellow might be better for the EGT gauge. 
I'm using white lighting for all instruments, but that's just what I've been throwing in. Which do you think is more realistic?
For me I'm having everything on an external dimming piece of hardware.
